// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtsLfgI6-QO3abvq5XOqT0XdE1oL9JFZk',
    appId: '1:409187249081:android:dc6937373a8475d154e468',
    messagingSenderId: '409187249081',
    projectId: 'home4u-3492b',
    storageBucket: 'home4u-3492b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqkkD7N2hFjJN_kEjTwFQ_fGygCQPHkXU',
    appId: '1:409187249081:ios:723404f61cf3c08754e468',
    messagingSenderId: '409187249081',
    projectId: 'home4u-3492b',
    storageBucket: 'home4u-3492b.firebasestorage.app',
    iosBundleId: 'com.example.home4u',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM4kQA7rInEySsXS-oenPw1RCleQdD8AU',
    appId: '1:409187249081:web:6c96c8e78b1ba17954e468',
    messagingSenderId: '409187249081',
    projectId: 'home4u-3492b',
    authDomain: 'home4u-3492b.firebaseapp.com',
    storageBucket: 'home4u-3492b.firebasestorage.app',
    measurementId: 'G-3QVGERC4JM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqkkD7N2hFjJN_kEjTwFQ_fGygCQPHkXU',
    appId: '1:409187249081:ios:723404f61cf3c08754e468',
    messagingSenderId: '409187249081',
    projectId: 'home4u-3492b',
    storageBucket: 'home4u-3492b.firebasestorage.app',
    iosBundleId: 'com.example.home4u',
  );

}