name: Android Fastlane Firebase App Distribution Workflow

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Flutter (Temporary for Dart & FVM)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6' # Match your .fvmrc version
          channel: stable

      - name: Install FVM
        run: dart pub global activate fvm

      - name: Install Flutter SDK via FVM
        run: |
          fvm install
          fvm flutter --version

      - name: Set FVM Flutter to PATH
        run: echo "$(fvm flutter sdk-path)/bin" >> $GITHUB_PATH

      - name: Get Dependencies
        run: fvm flutter pub get

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
          bundler-cache: true
          working-directory: android

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android